# Generated by Django 4.1.10 on 2023-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_mymodel_lesson_next_lesson_delete_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='next_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
