# Generated by Django 4.1.10 on 2023-10-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_lesson_next_lesson_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
    ]
