# Generated by Django 4.1.10 on 2023-10-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_lesson_rel', to='authentication.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='previous_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_lesson_rel', to='authentication.lesson'),
        ),
    ]
