# Generated by Django 4.1.10 on 2023-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_lesson_next_lesson_lesson_previous_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='next_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='previous_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
